site_name: The Spinning Sofa
site_dir: site

theme:
  name: material
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.details
  - pymdownx.tabbed
  - abbr
  - attr_list
  - def_list # Дополнительные возможности для форматирования списков (таск-листы и т. д.)
  - mdx_truly_sane_lists # Чтобы не нужно было добавлять пустую строку перед списком
  - mdx_breakless_lists # Чтобы не нужно было добавлять пустую строку перед списком
  - pymdownx.tasklist: # без него не отображаются чекбоксы
      custom_checkbox: false