site_name: The Spinning Sofa
site_dir: site
use_directory_urls: true

theme:
  logo: assets/favicon.png
  font:
    text: Jetbrains Mono
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Светлая тема

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Тёмная тема

markdown_extensions:
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.caption
  - md_in_html
  - abbr
  - attr_list
  - def_list # Дополнительные возможности для форматирования списков (таск-листы и т. д.)
  - mdx_truly_sane_lists # Чтобы не нужно было добавлять пустую строку перед списком
  - mdx_breakless_lists # Чтобы не нужно было добавлять пустую строку перед списком
  - pymdownx.tasklist: # без него не отображаются чекбоксы
      custom_checkbox: false